language: java

install: true

before_script:
  - touch $HOME/.gradle/gradle.properties
  - echo org.gradle.daemon=false >> $HOME/.gradle/gradle.properties

script:
  - ./gradlew :desktop:createExe

before_cache: rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - desktop/build/libs/*
    - desktop/build/launch4j/*.exe
  skip_cleanup: true
  on:
    tags: true

notification:
  slack:
    on_failure: always
    on_success: change
