language: java

install: true

script: ./gradlew :desktop:dist

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: desktop/build/libs/*
  skip_cleanup: true
  on:
    tags: true
